### ISSUE TITLE
StreamCopier.CopyStream does not copy the header of the file into the output

### ISSUE THREAD

**Issue by gabriel-vasile** [F0rzend/radiot_dumper#4]
After the discussion we had in https://github.com/gabriel-vasile/mimetype/issues/310, I had a look at the `copier.StreamCopier` and I think there is a problem.

step1: [extensionFromBody](https://github.com/F0rzend/radiot_dumper/blob/8e7cbb25a7ee073eda7e05ecfed4f5ffae6641b0/copier/stream_copier.go#L115-L122) will read file header in order to detect extension. It reads from a `bufio.Reader` which, in turn, reads from `resp.Body`. 
step2: Later, `io.Copy(output, resp.Body)` is called and, because the header was already read in step1, it is skipped.

You can confirm the problem by saving a URL twice:
- once using `radiot_dumper` (make sure [extensionFromBody](https://github.com/F0rzend/radiot_dumper/blob/8e7cbb25a7ee073eda7e05ecfed4f5ffae6641b0/copier/stream_copier.go#L94) is called when you test) 
- second time use the browser to save the file.
Then, compare the file saved with `radiot_dumper` and the file saved using the browser. The `radiot_dumper` file will be smaller because it is missing the header.

**Comment by F0rzend** [comment]
Unfortunately, the problem has not been resolved. Apparently the point is that this is a stream, and not just a recording
