### ISSUE TITLE
StreamCopier does not close resp.Body when done

### ISSUE THREAD

**Issue by gabriel-vasile** [F0rzend/radiot_dumper#5]
I just noticed `resp.Body.Close()` is never called by `StreamCopier` [here](https://github.com/F0rzend/radiot_dumper/blob/8e7cbb25a7ee073eda7e05ecfed4f5ffae6641b0/copier/stream_copier.go#L40-L87).

https://cs.opensource.google/go/go/+/refs/tags/go1.18.4:src/net/http/response.go;l=61-64
https://pkg.go.dev/net/http#example-Get

**Comment by F0rzend** [comment]
You are right. I forgot to close the body
